# Generated by Django 4.0.3 on 2022-04-28 18:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_publisher_alter_course_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 18, 42, 7, 714614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='publisher',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.publisher'),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 18, 42, 7, 722499, tzinfo=utc)),
        ),
    ]
