# Generated by Django 4.0.3 on 2022-05-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_course_created_alter_video_uploaded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ('id',), 'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги'},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='preview',
            new_name='preview_url',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='document',
            new_name='video_url',
        ),
    ]
