# Generated by Django 4.0.3 on 2022-05-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_step_options_rename_preview_video_preview_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['title'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='title',
        ),
    ]
