# Generated by Django 2.1.5 on 2022-03-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220308_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='list_id',
            new_name='list',
        ),
    ]
