# Generated by Django 4.0.3 on 2022-05-04 22:45

from django.db import migrations, models
import django.db.models.deletion
import main.utils.upload
import main.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_list_id_alter_todo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='is_done',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='due_on',
            new_name='due',
        ),
        migrations.AddField(
            model_name='todo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.upload.file_directory_path, validators=[main.utils.validators.validate_file_size, main.utils.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.upload.image_directory_path, validators=[main.utils.validators.validate_image_size, main.utils.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='todo',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.todolist'),
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
