# Generated by Django 4.0.3 on 2022-05-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_todolist_rename_is_done_todo_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='list',
            new_name='todo_list',
        ),
    ]
