# Generated by Django 4.0.3 on 2022-05-04 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_todo_created_alter_todo_due_alter_todo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_list',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.todolist'),
        ),
    ]
